name: Install `bevy_lint`
author: BD103
description: |
  Installs the Bevy linter and its required toolchain.

  This action currently uses Rustup to install the required toolchain components, and it uses
  `cargo install` to install the linter itself. The linter will be installed to `~/.cargo/bin` and
  will be available through the `PATH` by default.

  Note that this currently will override the default Rustup toolchain to nightly. You can fix this
  by calling `rustup default` after this action is run.
runs:
  using: composite
  steps:
    # Used to read `rust-toolchain.toml`.
    - name: Install Taplo
      uses: taiki-e/install-action@v2
      with:
        tool: taplo

    # Read `rust-toolchain.toml` to find the exact nightly toolchain the linter needs.
    - name: Extract toolchain
      id: toolchain
      shell: bash
      run: |
        CHANNEL=$(taplo get --file-path="${RUST_TOOLCHAIN_PATH}" 'toolchain.channel')
        COMPONENTS=$(taplo get --file-path="${RUST_TOOLCHAIN_PATH}" --separator=', ' 'toolchain.components')

        echo "channel=${CHANNEL}" >> "${GITHUB_OUTPUT}"
        echo "components=${COMPONENTS}" >> "${GITHUB_OUTPUT}"
      env:
        RUST_TOOLCHAIN_PATH: ${{ github.action_path }}/../rust-toolchain.toml

    - name: Install Rust toolchain and components
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.toolchain.outputs.channel }}
        components: ${{ steps.toolchain.outputs.components }}

    - name: Install `bevy_lint`
      shell: bash
      run: |
        rustup run "${RUST_CHANNEL}" cargo install \
          --path "${BEVY_LINT_PATH}" \
          --locked
      env:
        RUST_CHANNEL: ${{ steps.toolchain.outputs.channel }}
        # As the full contents of `TheBevyFlock/bevy_cli` is included alongside this action, we can
        # install the linter relative to the action path.
        BEVY_LINT_PATH: ${{ github.action_path }}
