name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  extract-rust-version:
    uses: ./.github/workflows/extract-rust-version.yml

  test:
    name: Run tests
    needs: extract-rust-version
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.channel }}
          components: ${{ needs.extract-rust-version.outputs.components }}

      # The linter's UI tests depend on Bevy with default features. This requires extra packages,
      # such as `alsa` and `udev`, to be installed on Linux.
      - name: Install Linux dependencies
        uses: bevyengine/bevy/.github/actions/install-linux-deps@v0.15.1

      - name: Run tests
        run: |
          cargo test new -- --nocapture
          # Workaround for https://github.com/rust-lang/cargo/issues/6669. `--doc` is incompatible
          # with `--all-targets`, so we run them separately.
          cargo test --workspace --all-features --doc

