name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  extract-rust-version:
    uses: ./.github/workflows/extract-rust-version.yml

  test:
    name: Run tests
    needs: extract-rust-version
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.channel }}
          components: ${{ needs.extract-rust-version.outputs.components }}

      - name: Cache build artifacts
        uses: Leafwing-Studios/cargo-cache@v2
        with:
          sweep-cache: true

      - name: Install Linux dependencies for Bevy
        uses: ./.github/actions/install-linux-deps

      - name: Run tests
        run: |
          cargo test --workspace --all-features --all-targets
          # Workaround for https://github.com/rust-lang/cargo/issues/6669. `--doc` is incompatible
          # with `--all-targets`, so we run them separately.
          cargo test --workspace --all-features --doc

  clippy:
    name: Check with Clippy
    needs: extract-rust-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.channel }}
          components: "${{ needs.extract-rust-version.outputs.components }}, clippy"

      - name: Cache build artifacts
        uses: Leafwing-Studios/cargo-cache@v2
        with:
          sweep-cache: true

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- --deny warnings

  rustfmt:
    name: Check with rustfmt
    needs: extract-rust-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.channel }}
          components: "${{ needs.extract-rust-version.outputs.components }}, rustfmt"

      - name: Run rustfmt
        run: cargo fmt --all --check

  docs:
    name: Build docs
    needs: extract-rust-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.channel }}
          components: ${{ needs.extract-rust-version.outputs.components }}

      - name: Cache build artifacts
        uses: Leafwing-Studios/cargo-cache@v2
        with:
          sweep-cache: true

      - name: Build documentation
        run: cargo doc --workspace --all-features --document-private-items --no-deps

  typos:
    name: Check for typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for typos
        id: typos
        uses: crate-ci/typos@v1.26.0

      - name: Print help on failure
        if: ${{ failure() && steps.typos.conclusion == 'failure' }}
        run: |
          echo 'To fix typos, please run `typos -w`.'
          echo 'To check for a diff, run `typos`.'
          echo 'You can install `typos` at <https://crates.io/crates/typos>.'
