name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  extract-rust-version:
    uses: ./.github/workflows/extract-rust-version.yml

  test:
    name: Run tests
    needs: extract-rust-version
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.channel }}
          components: ${{ needs.extract-rust-version.outputs.components }}

      # The linter's UI tests depend on Bevy with default features. This requires extra packages,
      # such as `alsa` and `udev`, to be installed on Linux.
      - name: Install Linux dependencies
        uses: bevyengine/bevy/.github/actions/install-linux-deps@v0.15.1

      - name: Cache build artifacts
        uses: Leafwing-Studios/cargo-cache@v2
        with:
          sweep-cache: true

      # We have a separate workspace where we execute the CLI in the E2E tests
      # It has it's own `target` folder, hence we need to cache it separately
      - name: Cache test workspace
        uses: Leafwing-Studios/cargo-cache@v2
        with:
          sweep-cache: true
          # The cache-group needs to be different to not collide with the cache for the test executing itself
          cache-group: "test_workspace-${{ hashFiles(env.workflow_path) }}-${{ github.job }}-${{ strategy.job-index }}"
          # cargo-cache doesn't support `working-directory` yet, we have to do it manually
          # See https://github.com/Leafwing-Studios/cargo-cache/issues/44
          cargo-target-dir: ./tests/bevy_cli_test/target
          manifest-path: ./tests/bevy_cli_test/Cargo.toml

      # The CLI's UI tests depend on Bevy with default features.
      # This requires extra packages, such as `alsa` and `udev`, to be installed on Linux.
      - name: Install Linux dependencies for Bevy
        uses: bevyengine/bevy/.github/actions/install-linux-deps@v0.15.1

      - name: Run tests
        run: |
          git clone https://github.com/TheBevyFlock/bevy_new_minimal.git
          cargo test new -- --nocapture
          # Workaround for https://github.com/rust-lang/cargo/issues/6669. `--doc` is incompatible
          # with `--all-targets`, so we run them separately.
          cargo test --workspace --all-features --doc

